steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta', 
    'functions',
    'deploy',
    'subscribe', 
    '--stage-bucket', '${PROJECT_ID}-cloud-build-notification',
    '--trigger-topic', 'cloud-builds',
    '--runtime', 'nodejs8'
    ]
